apiVersion: apps/v1
kind: Deployment
metadata:
  name: yeetsapi
  namespace: develop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: yeetsapi
    spec:
      containers:
        - name: yeetsapi
          image: mjhea0/flask-kubernetes:latest
          ports:
            - containerPort: 5000
